global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadence-frontend"
    static_configs:
      - targets: ["cadence:8000"]
        labels:
          service: "frontend"

  - job_name: "cadence-history"
    static_configs:
      - targets: ["cadence:8001"]
        labels:
          service: "history"

  - job_name: "cadence-matching"
    static_configs:
      - targets: ["cadence:8002"]
        labels:
          service: "matching"

  - job_name: "uber_cadence_worker"
    static_configs:
      - targets: ["cadence:8003"]
        labels:
          service: "worker"
